# This is used for local development
version: "3.9"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: product_inventory_db
    ports:
      - "27017:27017"
    restart: always